// QuantumNode is the gRPC interface a quantum-node container exposes
// (issue #20): a remote-callable core.QuantumBackend. core.RemoteBackend
// is the client side; cmd/quantum-node is the server side, wrapping a
// local (simulated) core.QuantumBackend.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: proto/quantumnode/quantumnode.proto

package quantumnode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Complex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Real          float64                `protobuf:"fixed64,1,opt,name=real,proto3" json:"real,omitempty"`
	Imag          float64                `protobuf:"fixed64,2,opt,name=imag,proto3" json:"imag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Complex) Reset() {
	*x = Complex{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Complex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complex) ProtoMessage() {}

func (x *Complex) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complex.ProtoReflect.Descriptor instead.
func (*Complex) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{0}
}

func (x *Complex) GetReal() float64 {
	if x != nil {
		return x.Real
	}
	return 0
}

func (x *Complex) GetImag() float64 {
	if x != nil {
		return x.Imag
	}
	return 0
}

// GateMatrix mirrors core.Gate: a named dim×dim unitary, row-major.
type GateMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	Entries       []*Complex             `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateMatrix) Reset() {
	*x = GateMatrix{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateMatrix) ProtoMessage() {}

func (x *GateMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateMatrix.ProtoReflect.Descriptor instead.
func (*GateMatrix) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{1}
}

func (x *GateMatrix) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GateMatrix) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *GateMatrix) GetEntries() []*Complex {
	if x != nil {
		return x.Entries
	}
	return nil
}

// StateVector mirrors core.QuantumState: amplitudes over a dim-dimensional
// HilbertSpace.
type StateVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dim           int32                  `protobuf:"varint,1,opt,name=dim,proto3" json:"dim,omitempty"`
	Amplitudes    []*Complex             `protobuf:"bytes,2,rep,name=amplitudes,proto3" json:"amplitudes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateVector) Reset() {
	*x = StateVector{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateVector) ProtoMessage() {}

func (x *StateVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateVector.ProtoReflect.Descriptor instead.
func (*StateVector) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{2}
}

func (x *StateVector) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *StateVector) GetAmplitudes() []*Complex {
	if x != nil {
		return x.Amplitudes
	}
	return nil
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gate          *GateMatrix            `protobuf:"bytes,1,opt,name=gate,proto3" json:"gate,omitempty"`
	State         *StateVector           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyRequest) GetGate() *GateMatrix {
	if x != nil {
		return x.Gate
	}
	return nil
}

func (x *ApplyRequest) GetState() *StateVector {
	if x != nil {
		return x.State
	}
	return nil
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *StateVector           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyResponse) GetState() *StateVector {
	if x != nil {
		return x.State
	}
	return nil
}

type MeasureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *StateVector           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureRequest) Reset() {
	*x = MeasureRequest{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureRequest) ProtoMessage() {}

func (x *MeasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureRequest.ProtoReflect.Descriptor instead.
func (*MeasureRequest) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{5}
}

func (x *MeasureRequest) GetState() *StateVector {
	if x != nil {
		return x.State
	}
	return nil
}

type MeasureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       int32                  `protobuf:"varint,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Probabilities []float64              `protobuf:"fixed64,2,rep,packed,name=probabilities,proto3" json:"probabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureResponse) Reset() {
	*x = MeasureResponse{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureResponse) ProtoMessage() {}

func (x *MeasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureResponse.ProtoReflect.Descriptor instead.
func (*MeasureResponse) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{6}
}

func (x *MeasureResponse) GetOutcome() int32 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

func (x *MeasureResponse) GetProbabilities() []float64 {
	if x != nil {
		return x.Probabilities
	}
	return nil
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{7}
}

// InfoResponse mirrors core.QuantumBackend's static metadata methods
// (Name, SupportedGates, Topology, NoiseModel), fetched once and cached
// by the client (core.RemoteBackend).
type InfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SupportedGates []string               `protobuf:"bytes,2,rep,name=supported_gates,json=supportedGates,proto3" json:"supported_gates,omitempty"`
	TopologyQubits int32                  `protobuf:"varint,3,opt,name=topology_qubits,json=topologyQubits,proto3" json:"topology_qubits,omitempty"`
	TopologyEdges  []int32                `protobuf:"varint,4,rep,packed,name=topology_edges,json=topologyEdges,proto3" json:"topology_edges,omitempty"` // flattened (a0,b0,a1,b1,...) pairs
	T1             float64                `protobuf:"fixed64,5,opt,name=t1,proto3" json:"t1,omitempty"`
	T2             float64                `protobuf:"fixed64,6,opt,name=t2,proto3" json:"t2,omitempty"`
	ReadoutError   float64                `protobuf:"fixed64,7,opt,name=readout_error,json=readoutError,proto3" json:"readout_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantumnode_quantumnode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_quantumnode_quantumnode_proto_rawDescGZIP(), []int{8}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetSupportedGates() []string {
	if x != nil {
		return x.SupportedGates
	}
	return nil
}

func (x *InfoResponse) GetTopologyQubits() int32 {
	if x != nil {
		return x.TopologyQubits
	}
	return 0
}

func (x *InfoResponse) GetTopologyEdges() []int32 {
	if x != nil {
		return x.TopologyEdges
	}
	return nil
}

func (x *InfoResponse) GetT1() float64 {
	if x != nil {
		return x.T1
	}
	return 0
}

func (x *InfoResponse) GetT2() float64 {
	if x != nil {
		return x.T2
	}
	return 0
}

func (x *InfoResponse) GetReadoutError() float64 {
	if x != nil {
		return x.ReadoutError
	}
	return 0
}

var File_proto_quantumnode_quantumnode_proto protoreflect.FileDescriptor

const file_proto_quantumnode_quantumnode_proto_rawDesc = "" +
	"\n" +
	"#proto/quantumnode/quantumnode.proto\x12\vquantumnode\"1\n" +
	"\aComplex\x12\x12\n" +
	"\x04real\x18\x01 \x01(\x01R\x04real\x12\x12\n" +
	"\x04imag\x18\x02 \x01(\x01R\x04imag\"b\n" +
	"\n" +
	"GateMatrix\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\x12.\n" +
	"\aentries\x18\x03 \x03(\v2\x14.quantumnode.ComplexR\aentries\"U\n" +
	"\vStateVector\x12\x10\n" +
	"\x03dim\x18\x01 \x01(\x05R\x03dim\x124\n" +
	"\n" +
	"amplitudes\x18\x02 \x03(\v2\x14.quantumnode.ComplexR\n" +
	"amplitudes\"k\n" +
	"\fApplyRequest\x12+\n" +
	"\x04gate\x18\x01 \x01(\v2\x17.quantumnode.GateMatrixR\x04gate\x12.\n" +
	"\x05state\x18\x02 \x01(\v2\x18.quantumnode.StateVectorR\x05state\"?\n" +
	"\rApplyResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.quantumnode.StateVectorR\x05state\"@\n" +
	"\x0eMeasureRequest\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.quantumnode.StateVectorR\x05state\"Q\n" +
	"\x0fMeasureResponse\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\x05R\aoutcome\x12$\n" +
	"\rprobabilities\x18\x02 \x03(\x01R\rprobabilities\"\r\n" +
	"\vInfoRequest\"\xe0\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fsupported_gates\x18\x02 \x03(\tR\x0esupportedGates\x12'\n" +
	"\x0ftopology_qubits\x18\x03 \x01(\x05R\x0etopologyQubits\x12%\n" +
	"\x0etopology_edges\x18\x04 \x03(\x05R\rtopologyEdges\x12\x0e\n" +
	"\x02t1\x18\x05 \x01(\x01R\x02t1\x12\x0e\n" +
	"\x02t2\x18\x06 \x01(\x01R\x02t2\x12#\n" +
	"\rreadout_error\x18\a \x01(\x01R\freadoutError2\xd0\x01\n" +
	"\vQuantumNode\x12>\n" +
	"\x05Apply\x12\x19.quantumnode.ApplyRequest\x1a\x1a.quantumnode.ApplyResponse\x12D\n" +
	"\aMeasure\x12\x1b.quantumnode.MeasureRequest\x1a\x1c.quantumnode.MeasureResponse\x12;\n" +
	"\x04Info\x12\x18.quantumnode.InfoRequest\x1a\x19.quantumnode.InfoResponseB\x1eZ\x1clinlang-go/proto/quantumnodeb\x06proto3"

var (
	file_proto_quantumnode_quantumnode_proto_rawDescOnce sync.Once
	file_proto_quantumnode_quantumnode_proto_rawDescData []byte
)

func file_proto_quantumnode_quantumnode_proto_rawDescGZIP() []byte {
	file_proto_quantumnode_quantumnode_proto_rawDescOnce.Do(func() {
		file_proto_quantumnode_quantumnode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quantumnode_quantumnode_proto_rawDesc), len(file_proto_quantumnode_quantumnode_proto_rawDesc)))
	})
	return file_proto_quantumnode_quantumnode_proto_rawDescData
}

var file_proto_quantumnode_quantumnode_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_quantumnode_quantumnode_proto_goTypes = []any{
	(*Complex)(nil),         // 0: quantumnode.Complex
	(*GateMatrix)(nil),      // 1: quantumnode.GateMatrix
	(*StateVector)(nil),     // 2: quantumnode.StateVector
	(*ApplyRequest)(nil),    // 3: quantumnode.ApplyRequest
	(*ApplyResponse)(nil),   // 4: quantumnode.ApplyResponse
	(*MeasureRequest)(nil),  // 5: quantumnode.MeasureRequest
	(*MeasureResponse)(nil), // 6: quantumnode.MeasureResponse
	(*InfoRequest)(nil),     // 7: quantumnode.InfoRequest
	(*InfoResponse)(nil),    // 8: quantumnode.InfoResponse
}
var file_proto_quantumnode_quantumnode_proto_depIdxs = []int32{
	0, // 0: quantumnode.GateMatrix.entries:type_name -> quantumnode.Complex
	0, // 1: quantumnode.StateVector.amplitudes:type_name -> quantumnode.Complex
	1, // 2: quantumnode.ApplyRequest.gate:type_name -> quantumnode.GateMatrix
	2, // 3: quantumnode.ApplyRequest.state:type_name -> quantumnode.StateVector
	2, // 4: quantumnode.ApplyResponse.state:type_name -> quantumnode.StateVector
	2, // 5: quantumnode.MeasureRequest.state:type_name -> quantumnode.StateVector
	3, // 6: quantumnode.QuantumNode.Apply:input_type -> quantumnode.ApplyRequest
	5, // 7: quantumnode.QuantumNode.Measure:input_type -> quantumnode.MeasureRequest
	7, // 8: quantumnode.QuantumNode.Info:input_type -> quantumnode.InfoRequest
	4, // 9: quantumnode.QuantumNode.Apply:output_type -> quantumnode.ApplyResponse
	6, // 10: quantumnode.QuantumNode.Measure:output_type -> quantumnode.MeasureResponse
	8, // 11: quantumnode.QuantumNode.Info:output_type -> quantumnode.InfoResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_quantumnode_quantumnode_proto_init() }
func file_proto_quantumnode_quantumnode_proto_init() {
	if File_proto_quantumnode_quantumnode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quantumnode_quantumnode_proto_rawDesc), len(file_proto_quantumnode_quantumnode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quantumnode_quantumnode_proto_goTypes,
		DependencyIndexes: file_proto_quantumnode_quantumnode_proto_depIdxs,
		MessageInfos:      file_proto_quantumnode_quantumnode_proto_msgTypes,
	}.Build()
	File_proto_quantumnode_quantumnode_proto = out.File
	file_proto_quantumnode_quantumnode_proto_goTypes = nil
	file_proto_quantumnode_quantumnode_proto_depIdxs = nil
}
