// QuantumNode is the gRPC interface a quantum-node container exposes
// (issue #20): a remote-callable core.QuantumBackend. core.RemoteBackend
// is the client side; cmd/quantum-node is the server side, wrapping a
// local (simulated) core.QuantumBackend.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: proto/quantumnode/quantumnode.proto

package quantumnode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuantumNode_Apply_FullMethodName   = "/quantumnode.QuantumNode/Apply"
	QuantumNode_Measure_FullMethodName = "/quantumnode.QuantumNode/Measure"
	QuantumNode_Info_FullMethodName    = "/quantumnode.QuantumNode/Info"
)

// QuantumNodeClient is the client API for QuantumNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuantumNodeClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	Measure(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*MeasureResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type quantumNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantumNodeClient(cc grpc.ClientConnInterface) QuantumNodeClient {
	return &quantumNodeClient{cc}
}

func (c *quantumNodeClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, QuantumNode_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantumNodeClient) Measure(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*MeasureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeasureResponse)
	err := c.cc.Invoke(ctx, QuantumNode_Measure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantumNodeClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, QuantumNode_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuantumNodeServer is the server API for QuantumNode service.
// All implementations must embed UnimplementedQuantumNodeServer
// for forward compatibility.
type QuantumNodeServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	Measure(context.Context, *MeasureRequest) (*MeasureResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedQuantumNodeServer()
}

// UnimplementedQuantumNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuantumNodeServer struct{}

func (UnimplementedQuantumNodeServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedQuantumNodeServer) Measure(context.Context, *MeasureRequest) (*MeasureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Measure not implemented")
}
func (UnimplementedQuantumNodeServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedQuantumNodeServer) mustEmbedUnimplementedQuantumNodeServer() {}
func (UnimplementedQuantumNodeServer) testEmbeddedByValue()                     {}

// UnsafeQuantumNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantumNodeServer will
// result in compilation errors.
type UnsafeQuantumNodeServer interface {
	mustEmbedUnimplementedQuantumNodeServer()
}

func RegisterQuantumNodeServer(s grpc.ServiceRegistrar, srv QuantumNodeServer) {
	// If the following call panics, it indicates UnimplementedQuantumNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuantumNode_ServiceDesc, srv)
}

func _QuantumNode_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantumNodeServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantumNode_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantumNodeServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantumNode_Measure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantumNodeServer).Measure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantumNode_Measure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantumNodeServer).Measure(ctx, req.(*MeasureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantumNode_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantumNodeServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantumNode_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantumNodeServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuantumNode_ServiceDesc is the grpc.ServiceDesc for QuantumNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuantumNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quantumnode.QuantumNode",
	HandlerType: (*QuantumNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _QuantumNode_Apply_Handler,
		},
		{
			MethodName: "Measure",
			Handler:    _QuantumNode_Measure_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _QuantumNode_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quantumnode/quantumnode.proto",
}
