//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HilbertSpace) DeepCopyInto(out *HilbertSpace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HilbertSpace.
func (in *HilbertSpace) DeepCopy() *HilbertSpace {
	if in == nil {
		return nil
	}
	out := new(HilbertSpace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HilbertSpace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HilbertSpaceList) DeepCopyInto(out *HilbertSpaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HilbertSpace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HilbertSpaceList.
func (in *HilbertSpaceList) DeepCopy() *HilbertSpaceList {
	if in == nil {
		return nil
	}
	out := new(HilbertSpaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HilbertSpaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HilbertSpaceSpec) DeepCopyInto(out *HilbertSpaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HilbertSpaceSpec.
func (in *HilbertSpaceSpec) DeepCopy() *HilbertSpaceSpec {
	if in == nil {
		return nil
	}
	out := new(HilbertSpaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HilbertSpaceStatus) DeepCopyInto(out *HilbertSpaceStatus) {
	*out = *in
	if in.EntangledWith != nil {
		in, out := &in.EntangledWith, &out.EntangledWith
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HilbertSpaceStatus.
func (in *HilbertSpaceStatus) DeepCopy() *HilbertSpaceStatus {
	if in == nil {
		return nil
	}
	out := new(HilbertSpaceStatus)
	in.DeepCopyInto(out)
	return out
}
